# fly.toml app configuration file generated for mapclientes-frontend on 2025-07-16T18:10:00Z
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "mapclientes-frontend"
primary_region = "gru"

[build]

[env]
  VITE_API_URL = "https://mapclientes-backend.fly.dev/api"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[[statics]]
  guest_path = "/app/dist"
  url_prefix = "/"
